// <auto-generated />
using System;
using ControleDeCinema.Infra.Compartilhado;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeCinema.Infra.Migrations
{
    [DbContext(typeof(ControleDeCinemaDbContext))]
    partial class ControleDeCinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleDeCinema.Dominio.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TBFuncionario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "12345678900",
                            Login = "c.tanaka",
                            Nome = "Caio Tanaka",
                            Senha = "sFQZT5W2kK8BUAO8uhhQ"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "98765432100",
                            Login = "junior.teixeira201",
                            Nome = "Júnior Teixeira",
                            Senha = "eNsoNQxmzglCOs3OK76a"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "45678912300",
                            Login = "marcia.silva0306",
                            Nome = "Márcia Silva",
                            Senha = "AW6m9OHzgB28v4ZNS5jY"
                        });
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModuloFilme.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<bool>("Estreia")
                        .HasColumnType("bit");

                    b.Property<int>("Genero_Id")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Genero_Id");

                    b.ToTable("TBFilme", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duracao = 90,
                            Estreia = false,
                            Genero_Id = 2,
                            Titulo = "Aladdin"
                        },
                        new
                        {
                            Id = 2,
                            Duracao = 127,
                            Estreia = true,
                            Genero_Id = 1,
                            Titulo = "Wolverine vs. Deadpool"
                        });
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModuloGenero.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TBGenero", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Animação"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Aventura"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Comédia"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Terror"
                        });
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModuloSessao.Ingresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<bool>("MeiaEntrada")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroAssento")
                        .HasColumnType("int");

                    b.Property<int>("Sessao_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("Sessao_Id");

                    b.ToTable("TBIngresso", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeiaEntrada = false,
                            NumeroAssento = 10,
                            Sessao_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            MeiaEntrada = true,
                            NumeroAssento = 25,
                            Sessao_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            MeiaEntrada = false,
                            NumeroAssento = 30,
                            Sessao_Id = 2
                        });
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModuloSessao.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.Property<bool>("Encerrada")
                        .HasColumnType("bit");

                    b.Property<int>("Filme_Id")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMaximoIngressos")
                        .HasColumnType("int");

                    b.Property<int>("Sala_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Filme_Id");

                    b.HasIndex("Sala_Id");

                    b.ToTable("TBSessao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Data = new DateTime(2024, 8, 7, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Encerrada = false,
                            Filme_Id = 2,
                            NumeroMaximoIngressos = 25,
                            Sala_Id = 2
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2024, 8, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Encerrada = false,
                            Filme_Id = 1,
                            NumeroMaximoIngressos = 35,
                            Sala_Id = 3
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2024, 8, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Encerrada = false,
                            Filme_Id = 1,
                            NumeroMaximoIngressos = 25,
                            Sala_Id = 3
                        },
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2024, 7, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Encerrada = true,
                            Filme_Id = 1,
                            NumeroMaximoIngressos = 20,
                            Sala_Id = 2
                        },
                        new
                        {
                            Id = 6,
                            Data = new DateTime(2024, 8, 2, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Encerrada = false,
                            Filme_Id = 2,
                            NumeroMaximoIngressos = 30,
                            Sala_Id = 1
                        },
                        new
                        {
                            Id = 5,
                            Data = new DateTime(2024, 8, 2, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Encerrada = true,
                            Filme_Id = 2,
                            NumeroMaximoIngressos = 28,
                            Sala_Id = 2
                        });
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModulosSala.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TBSala", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidade = 30,
                            Numero = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacidade = 35,
                            Numero = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacidade = 32,
                            Numero = 5
                        });
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModuloFilme.Filme", b =>
                {
                    b.HasOne("ControleDeCinema.Dominio.ModuloGenero.Genero", "Genero")
                        .WithMany("Filmes")
                        .HasForeignKey("Genero_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModuloSessao.Ingresso", b =>
                {
                    b.HasOne("ControleDeCinema.Dominio.Funcionario", null)
                        .WithMany("Ingressos")
                        .HasForeignKey("FuncionarioId");

                    b.HasOne("ControleDeCinema.Dominio.ModuloSessao.Sessao", "Sessao")
                        .WithMany("Ingressos")
                        .HasForeignKey("Sessao_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModuloSessao.Sessao", b =>
                {
                    b.HasOne("ControleDeCinema.Dominio.ModuloFilme.Filme", "Filme")
                        .WithMany("Sessoes")
                        .HasForeignKey("Filme_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleDeCinema.Dominio.ModulosSala.Sala", "Sala")
                        .WithMany("Sessoes")
                        .HasForeignKey("Sala_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filme");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.Funcionario", b =>
                {
                    b.Navigation("Ingressos");
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModuloFilme.Filme", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModuloGenero.Genero", b =>
                {
                    b.Navigation("Filmes");
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModuloSessao.Sessao", b =>
                {
                    b.Navigation("Ingressos");
                });

            modelBuilder.Entity("ControleDeCinema.Dominio.ModulosSala.Sala", b =>
                {
                    b.Navigation("Sessoes");
                });
#pragma warning restore 612, 618
        }
    }
}
